name: Sync Google Sheet

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download CSV from Google Drive
        run: |
          wget -O exported_sheet.csv "https://drive.google.com/uc?export=download&id=10ayRo2cP9jpg1tZ6E3Pap27OvrFi23fj"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add exported_sheet.csv
          git commit -m "Update exported Google Sheet"
          git push origin main
